import { ISchoolData } from "../types/@types";
import adisadel from "../asset/logos/adisadel.college.jpg";
import augustines from "../asset/logos/augustines.college.png";
import national from "../asset/logos/ghana.national.college.jpg";
import koforidua from "../asset/logos/ghana.shs.koforidua.png";
import KASHS from "../asset/logos/KASHS_Crestt.jpg";
import KNUST from "../asset/logos/knust_shs.webp";
import Kumasi from "../asset/logos/Kumasi-aca.webp";
import oda from "../asset/logos/oda.shs.jpg";
import Opoku from "../asset/logos/Opoku_Ware_School_crest.png";
import pope from "../asset/logos/pope.john.png";
import prempeh from "../asset/logos/prempeh.college.crest.jpg";
import louis from "../asset/logos/st.louis.shs.jpg";
import Swedru from "../asset/logos/swedru.shs.jpg";
import Peter from "../asset/logos/St._Peter's_Boys_Senior_High_School_logo.png";
import Sonrise from "../asset/logos/Sonrise.SHS.jpg";
import Ola from "../asset/logos/Ola.SHS.Ho.jpg";
import Sogakope from "../asset/logos/Sogakope.png";
import Chemu from "../asset/logos/st.louis.shs.jpg";
import PRESEC from "../asset/logos/Presbyterian_boys_secondary_logo_2.png";
import Accra from "../asset/logos/Accra_Academy_logo.jpg";
import Tamale from "../asset/logos/st.louis.shs.jpg";
import Bolgatanga from "../asset/logos/bolgatanga-senior-high.png";
import Konongo from "../asset/logos/bolgatanga-senior-high.png";

export const schoolData: ISchoolData[] = [
  {
    nameOfSchool: "BAGABAGA COLLEGE OF EDUCATION MODEL SCHOOL",
    region: "Northern",
    zone: "A",
    logo: louis,
    category: "1",
  },
  {
    nameOfSchool: "DAHEN SHELI JHS",
    region: "Northern",
    zone: "B",
    logo: Konongo,
    category: "2",
  },
  {
    nameOfSchool: "KAMINA BARRACKS JHS",
    region: "Northern",
    zone: "C",
    logo: Kumasi,
    category: "3",
  },
  {
    nameOfSchool: "KANVILLI PRESBY EXP. JHS",
    region: "Northern",
    zone: "B",
    logo: KNUST,
    category: "2",
  },
  {
    nameOfSchool: "KANVILLI R/C SCHOOL COMPLEX",
    region: "Northern",
    zone: "C",
    logo: prempeh,
    category: "3",
  },
  {
    nameOfSchool: "TAMALE INTERNATIONAL SCHOOL COMPLEX",
    region: "Northern",
    zone: "A",
    logo: KASHS,
    category: "1",
  },
  {
    nameOfSchool: "TIYUMBA M/A JHS",
    region: "Northern",
    zone: "C",
    logo: Opoku,
    category: "3",
  },
  {
    nameOfSchool: "ABE HALPERIN SCHOOL LTD",
    region: "Northern",
    zone: "A",
    logo: louis,
    category: "1",
  },
  {
    nameOfSchool: "ALHASSAN GBANZABA MEMORIAL SCHOOL",
    region: "Northern",
    zone: "B",
    logo: augustines,
    category: "2",
  },
  {
    nameOfSchool: "ETOILE ROYALE EDUCATIONAL CENTRE",
    region: "Northern",
    zone: "B",
    logo: Swedru,
    category: "2",
  },
  {
    nameOfSchool: "EVANGELICAL CHURCH OF GHANA SCHOOL COMPLEX",
    region: "Northern",
    zone: "B",
    logo: national,
    category: "2",
  },
  {
    nameOfSchool: "FAITH HILL COMMUNITY BASIC SCHOOL",
    region: "Northern",
    zone: "A",
    logo: louis,
    category: "1",
  },
  {
    nameOfSchool: "GREATER HEIGHTS INTERNATIONAL SCHOOL",
    region: "Northern",
    zone: "A",
    logo: adisadel,
    category: "1",
  },
  {
    nameOfSchool: "LAURENDA INTERNATIONAL SCHOOL",
    region: "Northern",
    zone: "A",
    logo: Peter,
    category: "1",
  },
  {
    nameOfSchool: "NORTHERN STAR SCHOOL COMPLEX",
    region: "Northern",
    zone: "A",
    logo: pope,
    category: "1",
  },
  {
    nameOfSchool: "PEGGY'S SCHOOL COMPLEX",
    region: "Northern",
    zone: "C",
    logo: koforidua,
    category: "3",
  },
  {
    nameOfSchool: "SHALOM ACADEMY INTERNATIONAL",
    region: "Northern",
    zone: "C",
    logo: oda,
    category: "3",
  },
  {
    nameOfSchool: "ROYAL UNIQUE SCHOOL COMPLEX",
    region: "Northern",
    zone: "B",
    logo: Sonrise,
    category: "2",
  },
  {
    nameOfSchool: "THE LITTLE WAY R/C JHS ",
    region: "Northern",
    zone: "C",
    logo: KASHS,
    category: "3",
  },
  {
    nameOfSchool: "KALADAN E P J H S ",
    region: "Northern",
    zone: "C",
    logo: Ola,
    category: "3",
  },
  {
    nameOfSchool: "ST. PAUL R/C J H S",
    region: "Northern",
    zone: "C",
    logo: Sogakope,
    category: "3",
  },
  {
    nameOfSchool: "FACHI LITTLE FLOWER",
    region: "Northern",
    zone: "B",
    logo: Chemu,
    category: "2",
  },
  {
    nameOfSchool: "H/ G S O S ",
    region: "Northern",
    zone: "A",
    logo: PRESEC,
    category: "1",
  },
  {
    nameOfSchool: "ELSIE LUND J H S",
    region: "Northern",
    zone: "B",
    logo: Accra,
    category: "3",
  },
  {
    nameOfSchool: "FATIH COLLEGE",
    region: "Northern",
    zone: "C",
    logo: Tamale,
    category: "3",
  },
  {
    nameOfSchool: "SHEPHED ACADEMY",
    region: "Northern",
    zone: "A",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "CENTRAL EDUCATIONAL FOUNDATION",
    region: "Northern",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "LABONE SDA CHURCH SCHOOL",
    district: "LA DADE-KOTOPON MUNICIPAL",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "GOSHEN COMMUNITY SCHOOL",
    district: "LA DADE-KOTOPON MUNICIPAL",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Pat Goshen Academy",
    district: "Ablekuma North",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "St Kizito R/C Basic",
    district: "AYAWASO EAST MUNICIPAL",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "ANCHILLAR PREPARATORY SCHOOL GA EAST",
    district: "GA EAST",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Aristoland",
    district: "Krowor Municipal",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Ashridge International Montessori School",
    district: "Krowor Municipal",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Holy KIDS",
    district: "Tema West Municipal",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "NEWMAN MEMORIAL",
    district: "ABLEKUMA CENTRAL",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Mary Star of the Sea",
    district: "Ga south",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "CJ SCHOOLS",
    district: "AYAWASO CENTRAL MUNICIPAL",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "LORD'S STAR INT SCHOOL",
    district: "Ashaiman Municipal",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "ST. MARTIN DE PORRES SCHOOL",
    district: "ABLEKUMA  WEST",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "ST. BERNADETTE SOUBIROUS SCHOOL",
    district: "ABLEKUMA  WEST",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "St. Theresa's School",
    district: "Accra Metro",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "Kiddie Class Preparatory",
    district: "Accra Metro",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "QueenLand International",
    district: "Tema West Municipal",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "LIBERTY HILLS INTERNATIONAL",
    district: "NINGO PRAMPRAM",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "Mizpah International School",
    district: "Okaikwei North",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "Glorich School",
    district: "Okaikwei North",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "L/A Memorial School",
    district: "Weija Gbawe",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Winners Family School",
    district: "Weija Gbawe",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "De Youngster's International School Adenta",
    district: "Adentan Municipal",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Tema Regular Baptist school",
    district: "Tema Metro",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Tema Brotherhood Preparatory school",
    district: "Tema Metro",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Glorious Hope Academy",
    district: "Ada West District",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "winningfaith International school",
    district: "Ada West District",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "SERVICES PRIMARY AND JHS",
    district: "LA DADE-KOTOPON MUNICIPAL",
    region: "Greater",
    zone: "3",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Prince of Peace",
    district: "Ablekuma North",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: " ST JOSEPH R/C JHS, FISE AMASAMAN",
    district: "Ga West Municipal",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Sakumono Complex 1&2 JHS",
    district: "Tema West Municipal",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "ATOMIC HILLS TWO",
    district: "GA EAST",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Quaye Nungua R C JHS",
    district: "Krowor Municipal",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Wajir Barracks 'B' Basic",
    district: "Ledzokuku Municipal",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "St.Anthony R/C Basic School",
    district: "GA NORTH MUNICIPAL",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Sakumono SDA Sea View",
    district: "Tema West Municipal ",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "ABOSSEY OKAI METHODIST BASIC",
    district: "ABLEKUMA CENTRAL",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Christ Fellowship Academy",
    district: "Ga south",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Kokomlemle 1 Basic",
    district: "Ayawaso Central",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Bonikope School Complex",
    district: "Ada West District",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Ashma No 1 JHS",
    district: "Ashaiman Municipal",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "UNIQUE CHILD INT. SCHOOL",
    district: "Ledzokuku Municipal",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "STAR OF THE SEA R/C BASIC",
    district: "ABLEKUMA  WEST",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Dawhenya Methodist B Basic",
    district: "Ningo-Prampram",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: " Kaneshie Awudome 1 JHS",
    district: "Accra Metro",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "PRAMPRAM D/A A BASIC",
    district: "NINGO PRAMPRAM",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Achimota Basic School",
    district: "Okaikwei North",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "Weija Presby JHS",
    district: "Weija Gbawe",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Mallam M/A 1 Basic",
    district: "Weija Gbawe",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Christ Faith Mission 1JHS",
    district: "Adentan Municipal",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "St.Paul Methodist JHS",
    district: "Tema Metro",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Smart International School",
    district: "Kpone",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Star Holy Kingdom Academy",
    district: "Gbetsile-Tema",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "Predes School complex",
    district: "Kpon  Katamanso",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Michel Camp One JHS",
    district: "Ashaiman Municipal",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "ST. Thomas International school",
    district: "LA DADE-KOTOPON MUNICIPAL",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Rising Star montessori",
    district: "Taifa",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "Faith Baptist JHS",
    district: "La Nkwantanang",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "Hannah School complex",
    district: "La Nkwantanang",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "West End InternationaL",
    district: "Ga south",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "Ringway Estate Basic",
    district: "Korle klottey",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "North Ridge Lyceum",
    district: "Accra Metro",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "Additrom Preparatory",
    district: "Korle klottey",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "ANCILAR PREPARATORY",
    district: "Achimota",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "CHRISTLOVE INTERNATIONAL",
    district: "Ada East",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Gods Grace Academy",
    district: "Okaikwei North",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "Lims Preparatory",
    district: "Shai Osu",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "Crown Prince International School",
    district: "Ablekuma North",
    region: "Greater",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "St. Paul's Lutheran school",
    district: "AYAWASO EAST MUNICIPAL",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Presec one JHS",
    district: "La-Nkwantanang",
    region: "Greater",
    zone: "A",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Villac International School",
    district: "GA NORTH MUNICIPAL",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Awudome 1 JHS",
    district: "Accra Metro",
    region: "Greater",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Best Brain International School",
    district: "Kronom-Abuohia",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "St. Anne's Anglican International School",
    district: "Ash-Town",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "1",
    seeded: true,
  },
  {
    nameOfSchool: "Angel Educational Complex",
    district: "Kronom Abuohia",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "1",
    seeded: true,
  },
  {
    nameOfSchool: "Riverside Academy",
    district: "Fumesua",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "1",
    seeded: true,
  },
  {
    nameOfSchool: "Bethelinter Academy",
    district: "Gyinase",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Weweso M/A JHS",
    district: "Kentinkrono",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "St. Anthony R/C JHS",
    district: "Bantama",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "State Boys M/A JHS",
    district: "Suame Roundabout",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Universal International School",
    district: "Mim",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Infant Jesus Lumen Christi School",
    district: "Ayeduase- Newsite (KNUST)",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Opoku Ware M/A JHS",
    district: "Santasi",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Asamang D/A JHS",
    district: "Asuofia",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Great Faith Rockery School",
    district: "Ahenema Kokoben",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Kyere Educational Complex",
    district: "Kenyasi-Truba",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Celestial Hope educational Complex",
    district: "Adugyama",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Trinity Foundation School",
    district: "Anwomaso",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Reach High School",
    district: "Kenyasi-Truba",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Adonia Angels Academy",
    district: "Tarkwa-Maakro",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "KNUST Basic Schools",
    district: "KNUST",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Rejoice National School",
    district: "Ahwiaa (Moro market)",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "BOPP D/A Basic School",
    district: "Adum Banso Estate",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "3",
  },
  {
    nameOfSchool: "Rockanje Presby Exp. JHS",
    district: "Old-Tafo",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Grace Light Educational Complex",
    district: "Ahenema Kokoben",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Matta Devi Basi School",
    district: "Gyinase",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Good Shepherd R/C JHS",
    district: "Ahinsan Estates",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Nana Quainoo Memorial School",
    district: "Boadi",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "New World School",
    district: "Atonsu",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Happy Royals International School",
    district: "Sawaba-New site",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Emmanuel Methodist JHS",
    district: "Oduom",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Global Community School",
    district: "Kotwi",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Konadu Yiadom M/A JHS",
    district: "Ash-Town",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Notre-Dame School",
    district: "Kenyase",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Salem Montessori School",
    district: "Oforikrom",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Manna International School",
    district: "Bremang UGC",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "St. louis Jubilee School",
    district: "KUMASI METROPOLITAN",
    region: "Ashanti",
    zone: "A",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "ABRAHAM LINCOLN INTERNATIONAL SCHOOL",
    district: "KUMASI METROPOLITAN",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "HOPFA EDUCATIONAL CENTRE BASIC SCHOOL",
    district: "ATWIMA NWABIAGYA MUNICIPAL",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "PARADISE HOPE INTERNATIONAL SCHOOL",
    district: "ATWIMA NWABIAGYA MUNICIPAL",
    region: "Ashanti",
    zone: "B",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "Uaddara NJHS",
    district: "KUMASI METROPOLITAN",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "2",
  },
  {
    nameOfSchool: "GOD'S GRACE INTERNATIONAL, ABUONTEM",
    district: "BEKWAI MUNICIPAL ",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "RIVERSIDE ACADEMY",
    district: "BOTSOMTWE DISTRICT",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "AGASSI MEMORIAL SCHOOL",
    district: "EJISU MUNICIPAL",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "MOTHER SMITH INTERNATIONAL  SCHOOL",
    district: "EJISU MUNICIPAL",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "PROGRESSIVE SHALOM INT.JHS",
    district: "JUABEN MUNICIPAL",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "GOLDEN STATE ACADEMY",
    district: "KUMASI METROPOLITAN",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "CHRIST FOUNDATION ACADEMY",
    district: "KUMASI METROPOLITAN",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "MOUNT OLIVET INT JHS",
    district: "KUMASI METROPOLITAN",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "WORLD LINKS ACADEMY ",
    district: "KUMASI METROPOLITAN",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: " ST THERESA R/C JHS",
    district: "KUMASI METROPOLITAN",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "SOS HERMANN GMNEINER",
    district: "Asokore Mampong ",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "MARTYRS OF UGANDA R/C JHS",
    district: "KUMASI METROPOLITAN",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "BUOKROM BETHEL METHODIST JHS",
    district: "KUMASI METROPOLITAN",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "ST. AGARTHA DA JHS",
    district: "kwabre East Municipal",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "PREMPEH EXP M/A BASIC C",
    district: "KWADASO MUNICIPAL",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "CALVARY METHODIST JHS",
    district: "EJISU MUNICIPAL",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "EJISU MODEL SCHOOL",
    district: "EJISU MUNICIPAL",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
  {
    nameOfSchool: "FUMESUA ANGLICAN SCHOO",
    district: "OFFINSO SOUTH MUNICIPAL",
    region: "Ashanti",
    zone: "C",
    logo: Bolgatanga,
    category: "1",
  },
];
